export const OPERATIONAL_STATUS = [
  'PENDIENTE',
  'EN_DIAGNOSTICO',
  'PROVEEDOR_NOTIFICADO',
  'EN_REPARACION',
  'RESPALDO_ENTREGADO',
  'REPARADO',
  'SUSTITUIDO',
  'NO_PROCEDE',
  'CERRADO'
]
